# Deploy Changed Controls Workflow
#
# This workflow intelligently detects which controls have changed and only
# deploys those controls. This is much faster and more efficient than deploying
# all controls on every commit. Uses direct script calls for portability.
#
# How it works:
#   1. Detects changed files using git diff
#   2. Extracts control directories from changed files
#   3. Validates only changed controls
#   4. Tests only changed controls
#   5. Packages only changed controls
#   6. Deploys only changed controls
#
# Benefits:
#   - Faster deployments
#   - Less API usage
#   - Quick feedback on changes
#   - Scales to large control repos

name: Deploy Changed Controls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ============================================================================
  # Detect Changed Controls
  # ============================================================================
  detect-changes:
    name: Detect Changed Controls
    runs-on: ubuntu-latest

    outputs:
      changed-controls: ${{ steps.detect.outputs.changed-controls }}
      has-changes: ${{ steps.detect.outputs.has-changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for accurate diff

      - name: Detect changed controls
        id: detect
        run: |
          # Get list of changed files
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PRs, compare with base branch
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            # For pushes, compare with previous commit
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo ""

          # Extract unique control directories
          # A control directory contains a contents.json file
          CHANGED_CONTROLS=$(echo "$CHANGED_FILES" | \
            grep -v "^examples/" | \
            grep -v "^scripts/" | \
            grep -v "^\.github/" | \
            cut -d'/' -f1 | \
            sort -u | \
            while read dir; do
              if [ -f "$dir/contents.json" ]; then
                echo "$dir"
              fi
            done)

          # Convert to space-separated list and JSON array
          if [ -z "$CHANGED_CONTROLS" ]; then
            echo "No control changes detected"
            echo "changed-controls=" >> $GITHUB_OUTPUT
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changed controls:"
            echo "$CHANGED_CONTROLS"

            # Space-separated for scripts
            SPACE_LIST=$(echo "$CHANGED_CONTROLS" | tr '\n' ' ')
            echo "changed-controls=$SPACE_LIST" >> $GITHUB_OUTPUT
            echo "has-changes=true" >> $GITHUB_OUTPUT

            echo ""
            echo "Will deploy: $SPACE_LIST"
          fi

  # ============================================================================
  # Validate & Test Changed Controls
  # ============================================================================
  validate-and-test:
    name: Validate and Test
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.has-changes == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install PyYAML
          pip install -r examples/testing/mappers/requirements.txt

      - name: Validate changed controls
        run: |
          chmod +x examples/testing/validation/validate-control.sh

          for control in ${{ needs.detect-changes.outputs.changed-controls }}; do
            echo "Validating $control"
            ./examples/testing/validation/validate-control.sh "$control"
          done

      - name: Test changed controls
        run: |
          for control in ${{ needs.detect-changes.outputs.changed-controls }}; do
            echo "Testing $control"

            # Test mappers if they exist
            if [ -d "$control/mappers" ]; then
              echo "Testing mappers for $control"
              cd examples/testing/mappers
              pytest -v || echo "No mapper tests found"
              cd ../../..
            fi
          done

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Test Rego rules
        run: |
          for control in ${{ needs.detect-changes.outputs.changed-controls }}; do
            if [ -f "$control/rule/rule.rego" ] && [ -f "$control/rule/rule_test.rego" ]; then
              echo "Testing Rego rules for $control"
              cd "$control/rule"
              opa test -v rule.rego rule_test.rego
              cd ../..
            fi
          done

  # ============================================================================
  # Deploy Changed Controls
  # ============================================================================
  deploy:
    name: Deploy Controls
    runs-on: ubuntu-latest
    needs: [detect-changes, validate-and-test]
    if: needs.detect-changes.outputs.has-changes == 'true' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Fianu CLI
        uses: fianulabs/actions@main
        with:
          version: ${{ secrets.FIANU_VERSION }}

      - name: Package changed controls
        run: |
          CONTROLS="${{ needs.detect-changes.outputs.changed-controls }}"
          echo "Packaging controls: $CONTROLS"
          ./scripts/package-all.sh $CONTROLS

      - name: Deploy controls
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_DEV_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_DEV_CLIENT_SECRET }}
          FIANU_HOST: https://fianu-dev.fianu.io
        run: |
          echo "Deploying to $FIANU_HOST"
          ./scripts/apply-all.sh dist/

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const controls = '${{ needs.detect-changes.outputs.changed-controls }}'.split(' ').filter(c => c);

            const summary = `## Deployment Summary

            **Changed Controls:** ${controls.length}

            ### Controls Deployed
            ${controls.map(c => `- \`${c}\``).join('\n')}

            ✅ All controls validated, tested, and ready to deploy!
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
