# Deploy Changed Controls Workflow
#
# This workflow intelligently detects which controls have changed and only
# deploys those controls. This is much faster and more efficient than deploying
# all controls on every commit.
#
# How it works:
#   1. Detects changed files using git diff
#   2. Extracts control directories from changed files
#   3. Validates only changed controls
#   4. Tests only changed controls
#   5. Packages only changed controls
#   6. Deploys only changed controls
#
# Benefits:
#   - Faster deployments
#   - Less API usage
#   - Quick feedback on changes
#   - Scales to large control repos
#
# Usage:
#   - Copy to .github/workflows/deploy-changed.yml
#   - Works automatically on push/PR

name: Deploy Changed Controls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ============================================================================
  # Detect Changed Controls
  # ============================================================================
  detect-changes:
    name: Detect Changed Controls
    runs-on: ubuntu-latest

    outputs:
      changed-controls: ${{ steps.detect.outputs.changed-controls }}
      has-changes: ${{ steps.detect.outputs.has-changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for accurate diff

      - name: Detect changed controls
        id: detect
        run: |
          # Get list of changed files
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PRs, compare with base branch
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            # For pushes, compare with previous commit
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo ""

          # Extract unique control directories
          # A control directory contains a contents.json file
          CHANGED_CONTROLS=$(echo "$CHANGED_FILES" | \
            grep -v "^examples/" | \
            grep -v "^scripts/" | \
            grep -v "^\.github/" | \
            cut -d'/' -f1 | \
            sort -u | \
            while read dir; do
              if [ -f "$dir/contents.json" ]; then
                echo "$dir"
              fi
            done)

          # Convert to JSON array
          if [ -z "$CHANGED_CONTROLS" ]; then
            echo "No control changes detected"
            echo "changed-controls=[]" >> $GITHUB_OUTPUT
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changed controls:"
            echo "$CHANGED_CONTROLS"

            # Convert to JSON array format
            JSON_ARRAY=$(echo "$CHANGED_CONTROLS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "changed-controls=$JSON_ARRAY" >> $GITHUB_OUTPUT
            echo "has-changes=true" >> $GITHUB_OUTPUT

            echo ""
            echo "JSON array: $JSON_ARRAY"
          fi

  # ============================================================================
  # Validate Changed Controls
  # ============================================================================
  validate:
    name: Validate Controls
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.has-changes == 'true'

    strategy:
      matrix:
        control: ${{ fromJson(needs.detect-changes.outputs.changed-controls) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyYAML

      - name: Validate control
        run: |
          chmod +x examples/testing/validation/validate-control.sh
          ./examples/testing/validation/validate-control.sh ${{ matrix.control }}

  # ============================================================================
  # Test Changed Controls
  # ============================================================================
  test:
    name: Test Controls
    runs-on: ubuntu-latest
    needs: [detect-changes, validate]
    if: needs.detect-changes.outputs.has-changes == 'true'

    strategy:
      matrix:
        control: ${{ fromJson(needs.detect-changes.outputs.changed-controls) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install testing dependencies
        run: pip install -r examples/testing/mappers/requirements.txt

      - name: Test mappers (if tests exist)
        run: |
          if [ -d "${{ matrix.control }}/mappers" ]; then
            echo "Testing mappers for ${{ matrix.control }}"
            # Copy test files to control directory if they exist
            if [ -f "examples/testing/mappers/test_detail.py" ]; then
              cd examples/testing/mappers
              pytest --cov=../../../${{ matrix.control }}/mappers -v || echo "No tests found"
            fi
          fi

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Test Rego rules (if tests exist)
        run: |
          if [ -f "${{ matrix.control }}/rule/rule.rego" ]; then
            cd "${{ matrix.control }}/rule"

            if [ -f "rule_test.rego" ]; then
              echo "Testing Rego rules for ${{ matrix.control }}"
              opa test -v rule.rego rule_test.rego
            else
              echo "No Rego tests found for ${{ matrix.control }}"
            fi
          fi

  # ============================================================================
  # Deploy Changed Controls
  # ============================================================================
  deploy:
    name: Deploy Controls
    runs-on: ubuntu-latest
    needs: [detect-changes, test]
    if: needs.detect-changes.outputs.has-changes == 'true' && github.event_name == 'push'

    permissions:
      id-token: write
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Fianu CLI
        uses: fianulabs/actions@main
        with:
          version: ${{ secrets.FIANU_VERSION }}

      - name: Package changed controls
        id: package
        uses: ./.github/actions/package-controls
        with:
          control-list: ${{ needs.detect-changes.outputs.changed-controls }}

      - name: Deploy controls
        id: deploy
        uses: ./.github/actions/apply-controls
        with:
          client-id: ${{ secrets.FIANU_DEV_CLIENT_ID }}
          client-secret: ${{ secrets.FIANU_DEV_CLIENT_SECRET }}
          host: https://fianu-dev.fianu.io
          rate-limit-delay: 2
          fail-on-error: true

      - name: Display results
        uses: ./.github/actions/display-results
        with:
          deployed-count: ${{ steps.deploy.outputs.deployed-count }}
          failed-count: ${{ steps.deploy.outputs.failed-count }}
          total-count: ${{ steps.deploy.outputs.total-count }}
          failed-packages: ${{ steps.deploy.outputs.failed-packages }}
          success-rate: ${{ steps.deploy.outputs.success-rate }}
          summary: ${{ steps.deploy.outputs.summary }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const summary = `## Deployment Summary

            **Changed Controls:** ${{ steps.deploy.outputs.total-count }}
            **Successfully Deployed:** ${{ steps.deploy.outputs.deployed-count }}
            **Failed:** ${{ steps.deploy.outputs.failed-count }}
            **Success Rate:** ${{ steps.deploy.outputs.success-rate }}%

            ### Controls Deployed
            ${{ needs.detect-changes.outputs.changed-controls }}

            ${{ steps.deploy.outputs.failed-count > 0 && '### Failed Deployments\n' + steps.deploy.outputs.failed-packages || '✅ All controls deployed successfully!' }}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
